CREATE TABLE IF NOT EXISTS profiles (
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY UNIQUE,
	td TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	email VARCHAR(50) UNIQUE,
	coins INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS questMarkers (
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY UNIQUE,
	latitude FLOAT NOT NULL,
	longitude FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS profilesQuests (
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY UNIQUE,
	CONSTRAINT profilesID FOREIGN KEY (id) REFERENCES profiles(id),
	CONSTRAINT questsID FOREIGN KEY (id) REFERENCES questMarkers(id)
);
