CREATE TABLE IF NOT EXISTS mailinglist (
	userID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY UNIQUE,
	td TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	email VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS quests (
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY UNIQUE,
	latitude FLOAT NOT NULL,
	longitude FLOAT NOT NULL
);
