CREATE TABLE IF NOT EXISTS signups (
	email VARCHAR(50) UNIQUE,
	verify INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS profiles (
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY UNIQUE,
	td TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	email VARCHAR(50) UNIQUE,
	coins INTEGER DEFAULT 0,
        jewels INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS questMarkers (
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY UNIQUE,
	latitude FLOAT NOT NULL,
	longitude FLOAT NOT NULL
);


